### ISSUE TITLE
missing lazy functions

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#204]
the following functions  `py-polars/polars/functions/lazy.py` are not yet translated in `./R/functions__lazy.R` (file renamed in #196).

tag any merged translated, or write your name after to reserve it for a PR

- [x] pl$map
- [x] pl$apply
- [x] pl$fold (#403)
- [x] pl$reduce (#403)
- [ ] pl$cum_fold
- [ ] pl$cum_reduce
- [x] pl$exclude
- [ ] pl$groups (maybe wait for https://github.com/pola-rs/polars/issues/13274)
- [ ] pl$format
- [x] pl$cumsum
- [x] pl$any
- [x] pl$all cover bitwise also
- [x] pl$quantile
- [x] pl$arange
- [x] pl$collect_all => @etiennebacher: I don't think we need to implement this, it's basically `lapply(<list of LF>, \(x) x$collect())`
- [ ] pl$repeat
- [x] pl$arg_where
- [x] pl$spearman_rank_corr --- Deprecated in pypolars
- [x] pl$pearson_corr --- Deprecated in pypolars
- [x] pl$corr (#351)
- [x] pl$cov (#351)
- [x] pl$arg_sort_by
- [x] pl$duration
- [x] pl$datetime_
- [x] pl$date_
- [x] pl$concat_str_ (#349)
- [x] pl$from_epoch (#708)
- [x] pl$rolling_cov (#351)
- [x] pl$rolling_corr (#351)

**Comment by eitsupi** [comment]
I close it because it is outdated.
